### ISSUE TITLE
Cant stop wroking

### ISSUE THREAD

**Issue by akwaro123** [Kacper1263/Quizer#9]
Project is not responding after touches

**Comment by Kacper1263** [comment]
It's working 24/7 on our servers, maybe you have wrong Node.JS version

**Comment by akwaro123** [comment]
Thanks for reply, its not. It's clearly saying apiPort dont exist. Can we add on facebook and fix it togheter?

**Comment by Kacper1263** [comment]
Did you create the config.json file correctly?

**Comment by akwaro123** [comment]
**no, thank you extactly. It fixed a lot. We can add on facebook? i will send you many thanks**

**Comment by akwaro123** [comment]
is it you? https://www.facebook.com/Kacper1263 kacper1263

**Comment by Kacper1263** [comment]
I don't use facebook 😁 but I'm happy its working now

**Comment by akwaro123** [comment]
dont close

**Comment by Maciej-Wilkosz** [comment]
close close
